project:
  type: website
  output-dir: docs

website:
  title: "Tobacco-Related Cancer Deaths"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.html
        text: Home
      - href: abstract.html
        text: Abstract
      - href: background.html
        text: Background
      - href: goals.html
        text: Project Goals
      - href: methods.html
        text: Methods
      - href: results.html
        text: Results
      - href: conclusion.html
        text: Conclusion & Recommendations

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    code-fold: true