project:
  type: website
  output-dir: docs


website:
  site-url: https://data-sci-245-sp25.github.io/AC-Project/
  title: "Tobacco-Related Cancer Deaths"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: abstract.qmd
        text: Abstract
      - href: background.qmd
        text: Background
      - href: goals.qmd
        text: Project Goals
      - href: methods.qmd
        text: Methods
      - href: results.qmd
        text: Results
      - href: conclusion.qmd
        text: Conclusion & Recommendations

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    code-fold: true